route:
  receiver: "webhook"
  group_by: ["alertname", "instance", "groupname"]
  group_wait: 5s
  group_interval: 5s
  repeat_interval: 5m

receivers:
  - name: "webhook"
    webhook_configs:
      - url: "http://localhost:9200/alert"
        send_resolved: true
